project:
  type: website
  output-dir: docs

website:
  title: "demo-website"
  navbar:
    left:
      - href: quarto_intro.qmd
        text: "Introduction"
      - href: index.qmd
        text: "Quarto website"
      - href: quarto_slides.qmd
        text: "Slides"
      - href: quarto_paper.qmd
        text: "Paper"
      - href: quarto_interactive.qmd
        text: "Getting fancy"
    tools:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/ucldw25-quarto-showcase

format:
  html:
    theme:
      - cosmo  #flatly
    css: styles.css
    toc: true



